"""fix

Revision ID: 9390a7098963
Revises: 6eeb7fbffbd8
Create Date: 2021-11-29 00:31:42.739978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9390a7098963'
down_revision = '6eeb7fbffbd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'social_account', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'social_account', type_='unique')
    # ### end Alembic commands ###
