"""empty message

Revision ID: b7d03c4f3fc5
Revises: f9410dc5c2c3
Create Date: 2021-11-09 16:08:16.797568

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b7d03c4f3fc5'
down_revision = 'f9410dc5c2c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('info', sa.String(), nullable=True))
    op.drop_column('history', 'additional_info')
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('user', 'updated_on')
    op.drop_column('user', 'active')
    op.drop_column('user', 'created_on')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('updated_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    op.add_column('history', sa.Column('additional_info', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('history', 'info')
    # ### end Alembic commands ###
