"""empty message

Revision ID: e96d3f443bca
Revises: aab60adedd40
Create Date: 2021-11-17 19:06:26.556062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e96d3f443bca'
down_revision = 'aab60adedd40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('permission', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('role', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('permission', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
