# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import notify_registration_pb2 as notify__registration__pb2


class NotifyRegisterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UserRegisterEvent = channel.unary_unary(
                '/NotifyRegister/UserRegisterEvent',
                request_serializer=notify__registration__pb2.UserRegisteredRequest.SerializeToString,
                response_deserializer=notify__registration__pb2.UserRegisteredResponse.FromString,
                )


class NotifyRegisterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UserRegisterEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NotifyRegisterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UserRegisterEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.UserRegisterEvent,
                    request_deserializer=notify__registration__pb2.UserRegisteredRequest.FromString,
                    response_serializer=notify__registration__pb2.UserRegisteredResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'NotifyRegister', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NotifyRegister(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UserRegisterEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/NotifyRegister/UserRegisterEvent',
            notify__registration__pb2.UserRegisteredRequest.SerializeToString,
            notify__registration__pb2.UserRegisteredResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
