# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notify_registration.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='notify_registration.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19notify_registration.proto\"G\n\x15UserRegisteredRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\r\n\x05login\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\"(\n\x16UserRegisteredResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\x32X\n\x0eNotifyRegister\x12\x46\n\x11UserRegisterEvent\x12\x16.UserRegisteredRequest\x1a\x17.UserRegisteredResponse\"\x00\x62\x06proto3'
)




_USERREGISTEREDREQUEST = _descriptor.Descriptor(
  name='UserRegisteredRequest',
  full_name='UserRegisteredRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='email', full_name='UserRegisteredRequest.email', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='login', full_name='UserRegisteredRequest.login', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='password', full_name='UserRegisteredRequest.password', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=100,
)


_USERREGISTEREDRESPONSE = _descriptor.Descriptor(
  name='UserRegisteredResponse',
  full_name='UserRegisteredResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='UserRegisteredResponse.result', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=142,
)

DESCRIPTOR.message_types_by_name['UserRegisteredRequest'] = _USERREGISTEREDREQUEST
DESCRIPTOR.message_types_by_name['UserRegisteredResponse'] = _USERREGISTEREDRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserRegisteredRequest = _reflection.GeneratedProtocolMessageType('UserRegisteredRequest', (_message.Message,), {
  'DESCRIPTOR' : _USERREGISTEREDREQUEST,
  '__module__' : 'notify_registration_pb2'
  # @@protoc_insertion_point(class_scope:UserRegisteredRequest)
  })
_sym_db.RegisterMessage(UserRegisteredRequest)

UserRegisteredResponse = _reflection.GeneratedProtocolMessageType('UserRegisteredResponse', (_message.Message,), {
  'DESCRIPTOR' : _USERREGISTEREDRESPONSE,
  '__module__' : 'notify_registration_pb2'
  # @@protoc_insertion_point(class_scope:UserRegisteredResponse)
  })
_sym_db.RegisterMessage(UserRegisteredResponse)



_NOTIFYREGISTER = _descriptor.ServiceDescriptor(
  name='NotifyRegister',
  full_name='NotifyRegister',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=144,
  serialized_end=232,
  methods=[
  _descriptor.MethodDescriptor(
    name='UserRegisterEvent',
    full_name='NotifyRegister.UserRegisterEvent',
    index=0,
    containing_service=None,
    input_type=_USERREGISTEREDREQUEST,
    output_type=_USERREGISTEREDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_NOTIFYREGISTER)

DESCRIPTOR.services_by_name['NotifyRegister'] = _NOTIFYREGISTER

# @@protoc_insertion_point(module_scope)
